---
title: "RNA-seq Analysis of COL, log2-2, and abi5-7 Under GM & LEU Conditions"
subtitle: "Differential Expression, Clustering, and Stress-Response Profiling"
author: "Iliana Castillo-Machuca — Virginia Tech, School of Plant & Environmental Sciences"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    code_folding: hide
    theme: cosmo
    highlight: tango
    df_print: paged
    includes:
      after_body: style.html
---

# 1. CLEAR ENVIRONMENT
```{r CLEAR-ENVIRONMENT}
#------------------------ CLEAN ENVIRONMENT ------------------------#
rm(list = ls(envir = .GlobalEnv, all.names = TRUE)) # Clear wrkspace
invisible(gc()) # Garbage collection to free memory

# Global options for consistency
options(
  max.print              = 50000, # Cap console output
  scipen                 = 0,     # Avoid sci note 999, 0 if you want sci.note
  stringsAsFactors       = FALSE, # Keep strings as character
  dplyr.summarise.inform = FALSE, # Suppress dplyr's messages
  digits                 = 4      # Number of digits to print
  )

set.seed(1234)
#------------------------ PROJECT INFO ------------------------# 
info <- list(
  Title             = "AMINO ACID TOXICITY (LOG2 ABI5) ANALYSIS",
  R_Version         = R.version$version.string,
  Working_Directory = getwd(),
  Timestamp         = format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  )

separator <- paste0("\n", strrep("=", 80), "\n")
cat("PROJECT:", info$Title, "\n")
cat(separator)

cat("R Version:", info$R_Version, "\n")
cat("Working Directory:", info$Working_Directory, "\n")
cat("Timestamp:", info$Timestamp, "\n")
cat(separator)

info$renv_active <- renv::project()
cat("renv Project:", info$renv_active, "\n")

info$Git_Commit <- system("git rev-parse --short HEAD", intern = TRUE)
cat("Git Commit:", info$Git_Commit, "\n")

#sessionInfo()
#renv::init() #first time use to make an environment with the packages
```
# 2. Packages, Load, and Installation
```{r INSTALL-PACKAGES, message=FALSE}
#------------------------ LOAD PACKAGES ------------------------#
cran_packages <- c(
  "tidyverse",    # dplyr, ggplot2, tidyr, purrr, stringr, readr, forcats
  "ggrepel",      # Add non-overlapping text labels to ggplot2
  "pheatmap",     # Clustered heat maps
  "RColorBrewer", # Color palettes
  "dendextend",   # Dendrogram
  "writexl",      # Excel export
  "ggdendro",
  "DiagrammeR",
  "gridExtra",
  "grid",
  "rmarkdown",
  "yaml",
  "BiocManager",
  "factoextra",
  "ggplot2",
  "VennDiagram",
  "grid",
  "cluster",
  "enrichplot",
  "ggVennDiagram",
  "tidytext"
)
bioc_packages <- c(
  "DESeq2",          # Differential expression analysis
  "EnhancedVolcano",
  "rstudioapi",
  "apeglm",
  "org.At.tair.db",  # Arabidopsis thaliana annotations
  "clusterProfiler"  # GO/KEGG enrichment analysis and GSEA
)

#------------------------ INSTALL CRAN PACKAGES ------------------------#
new_cran <- cran_packages[!sapply(cran_packages, requireNamespace, quietly = TRUE)]
if (length(new_cran) > 0) install.packages(new_cran)

#------------------------ INSTALL BIOCONDUCTOR ------------------------#
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

new_bioc <- bioc_packages[!sapply(bioc_packages, requireNamespace, quietly = TRUE)]
if (length(new_bioc) > 0) BiocManager::install(new_bioc, ask = FALSE)

#------------------------ LOAD PACKAGES ------------------------#
invisible(lapply(cran_packages, library, character.only = TRUE))
invisible(lapply(bioc_packages, library, character.only = TRUE))

#------------------------ WORKING DIRECTORY ------------------------# 
cat("Working directory:", getwd(), "\n")

#renv::status()
#renv::snapshot()
```
# 3. Folder Setup
```{r FOLDERS message=FALSE}
#------------------------ SET OUTPUT DIRECTORY ------------------------#  
graphics_dir <- file.path("Results/Graphics")
tables_dir   <- file.path("Results/Tables") 
procdata_dir <- file.path("Results/Processed_data")

dirs <- c(graphics_dir, tables_dir, procdata_dir)

# Create the dirs if they don't exist
invisible(sapply(dirs,
                 function(d) {
                   if (!dir.exists(d)) {
                     dir.create(d, recursive = TRUE, showWarnings = FALSE)
                     } } ) )
```
# 4. Read In Raw Counts, Prep Data
```{r READ-COUNTS, message=FALSE}
#------------------------ LOAD GENOME ALIGNMENT FILES ------------------------#
featcount  <- read_tsv("./Data_Repository/Log2ABA.featcount.txt", skip = 1)
count_cols <- colnames(featcount)[7:ncol(featcount)] # backup OG names except first 7 col

read.count <- featcount %>% dplyr::select(all_of(count_cols)) %>% as.matrix()
rownames(read.count) <- featcount[[1]] #Add GENES / names

#------------------------ SET NAMES & INFO ------------------------#
info <- tibble(old = count_cols) |>
  tidyr::separate_wider_delim(old,
                              delim    = "_",
                              names    = c("rep", "genotype", "treatment"),
                              too_many = "drop"
                              ) |>
  mutate(genotype_clean = case_when(genotype == "ABI" ~ "abi5-7",
                                    genotype == "LOG" ~ "log2-2",
                                    genotype == "COL" ~ "COL",
                                    TRUE ~ genotype),
         new = paste(genotype_clean, treatment, rep, sep = "_"))
colnames(read.count) <- info$new

#------------------------ DESIGN SAMPLE INFO ------------------------#
sample_names <- colnames(read.count)

# Extract genotype (COL, log2-2, abi5-7)
group_setup <- stringr::str_extract(sample_names, "^(abi5-7|COL|log2-2)")
genotype    <- factor(group_setup, levels = c("COL","log2-2","abi5-7"))

# Extract treatment (GM or LEU)
treatment <- stringr::str_extract(sample_names, "(GM|LEU)")
treatment <- factor(treatment, levels = c("GM", "LEU"))

# Build sample info
sample_info <- data.frame(row.names = sample_names,
                          genotype  = genotype,
                          treatment = treatment)
stopifnot(all(rownames(sample_info) == colnames(read.count))) # Safety check

#------------------------ SAVE ------------------------#
#read.count <- tibble::rownames_to_column(as.data.frame(as.matrix(read.count)), "GeneID")
## Convert to DF with gene IDs
#raw_counts_df <- tibble::rownames_to_column(raw_counts_df, "GeneID")

#write_csv(raw_counts_df, file.path(tables_dir, "raw_counts_clean.csv"))
#writexl::write_xlsx(raw_counts_df, file.path(tables_dir, "LOG2_ABI_raw_counts_clean.xlsx"))
```
# 5. THRESHOLDS, COLORS
```{r THRESHOLDS}
#------------------------ Set Values: P.VAL, LFC ------------------------#
pad        <- 0.05
lfc_thresh <- 1.0

#------------------------ COLORS ------------------------#
colors <- c("COL" = "#32BECC",   # blue curacao
            "abi5-7" = "#F9AC2F",   # citrus
            "log2-2" = "#F07BA5"    # pink cosmos
            )

#------------------------ COLOR SWATCH ------------------------# 
df_colors <- data.frame(Condition = names(colors), Color = colors)

ggplot(df_colors, aes(x = Condition, y = 1, fill = Condition)) + geom_tile() + scale_fill_manual(values = colors) + theme_void() + theme( legend.position = "none", plot.margin = margin(2, 2, 2, 2)) + ggtitle("Color Swatch")
```
# 6. DESEQ2
```{r DESeq-run, message=FALSE}
#------------------------ DESEQ2 MATRIX ------------------------#
dds <- DESeqDataSetFromMatrix(countData = read.count,
                              colData   = sample_info,
                              design    = ~ genotype * treatment) 

# genotype * treatment <- asks whether the leucine response differs by genotype
#------------------------ Pre-filter ------------------------#
keep <- rowSums(counts(dds)) >= 10
dds  <- dds[keep, ]

#------------------------ RUN DESEQ2 ------------------------#
dds  <- DESeq(dds)

#------------------------ CHECK & SAVE ------------------------#
#dds$treatment #check levels
#dds$genotype
resultsNames(dds)

## Save full DESeq object
#saveRDS(dds, file.path(procdata_dir, "dds_IM_H_UM.rds"))
#writeLines(resultsNames(dds), file.path(procdata_dir, "coefficient_names.txt"))
```
# 7. VST; NORM COUNTS
```{r VST}
#------------------------ VST ------------------------#
## Variance stabilizing transformation
vsd <- vst(dds, blind = FALSE) # blind ignores design
colnames(vsd) <- rownames(sample_info) ## Sample names, match to colData
stopifnot(all(colnames(vsd) == rownames(colData(dds))))  # Check

mat <- assay(vsd) #expression matrix
```
# 8. PCA; PLOT
```{r PCA}
#------------------------ PCA; PLOT ------------------------#
pca_data   <- plotPCA(vsd, intgroup = c("genotype", "treatment"), returnData = TRUE)
percentVar <- round(100 * attr(pca_data, "percentVar"))

p_pca      <- ggplot(pca_data, 
                aes(PC1, PC2, color = genotype, shape = treatment)) +
  geom_point(size = 5, stroke = 1.5, alpha = 0.85) +
  scale_color_manual(values = colors, name = "genotype") +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  geom_text_repel(aes(label = name),                 
                  box.padding = 0.35, 
                  max.overlaps = Inf,  # Show all labels
                  size = 3.5, 
                  segment.color = "red",
                  segment.size = 0.3,
                  bg.color = "white", 
                  bg.r = 0.1) +
  labs(title = "Sample Clustering (Variance-Stabilized Counts)",
       subtitle = paste("PC1:", round(percentVar[1],1), "% variance |",
                       "PC2:", round(percentVar[2],1), "% variance")) +
  theme_classic(base_size = 13) +
  theme(legend.position = "bottom", 
        legend.title = element_text(face = "bold"),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
        plot.subtitle = element_text(hjust = 0.5, size = 12),
        panel.grid.minor = element_blank())
print(p_pca)

#------------------------ SAVE ------------------------#
#ggsave(file.path(graphics_dir, "LOG2_ABI5.png"), p_pca, width = 8, height = 8, dpi = 300)
```
# 9. SAMPLE DISTANCE
```{r SAMPLE DISTANCE}
#------------------------ SAMPLE DISTANCE ------------------------#
sample_dist <- dist(t(assay(vsd)))  # t samples as rows
hc          <- hclust(sample_dist, method = "ward.D2")
dend_data   <- ggdendro::dendro_data(hc)

#------------------------ PLOT SAMPLE DISTANCE ------------------------#
label_df <- dend_data$labels # Create label dataframe and add metadata

sample_info <- as.data.frame(colData(vsd))

label_df$genotype  <- sample_info$genotype[match(label_df$label, rownames(sample_info))]
label_df$treatment <- sample_info$treatment[match(label_df$label, rownames(sample_info))]
label_df$color     <- colors[label_df$genotype]

# Bold LEU samples
label_df$fontface <- ifelse(label_df$treatment == "LEU", "bold", "plain")

p_dend <- ggplot() +
  geom_segment(data = ggdendro::segment(dend_data),
               aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data = label_df, 
            aes(x = x,
                y = y,
                label = label,
                color = color,
                fontface = fontface),
            hjust = -0.1,
            size = 3.5) +
  scale_color_identity() +
  coord_flip() +
  scale_y_reverse(expand = c(0.2, 0)) +
  ggdendro::theme_dendro() +
  labs(title = "VST Clustering (Ward.D2)",
       subtitle = "Color = Genotype, Bold = LEU") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
p_dend

#------------------------ SAVE ------------------------#
#ggsave(file.path(graphics_dir,"Distance_tree.png"), p_dend, width = 8, height = 6 )
```
# 10. SAMPLE HEATMAP
```{r}
sample_dist <- dist(t(assay(vsd)))
sampleDistMatrix <- as.matrix(sample_dist)

rownames(sampleDistMatrix) <- paste( colData(dds)$genotype, colData(dds)$treatment, sep = "_")
colnames(sampleDistMatrix) <- rownames(sampleDistMatrix)

p2 <- pheatmap( sampleDistMatrix, clustering_distance_rows = sample_dist, clustering_distance_cols = sample_dist, main = "Sample Distance Heatmap")
p2

#------------------------ SAVE ------------------------#
#ggsave(file.path(graphics_dir, "sample_clustering_colored.png"), 
#       p_dend, width = 12, height = 8, dpi = 300)

#------------------------ Correlation Distance ------------------------#
# Correlation distance
sampleDist_cor   <- as.dist(1 - cor(assay(vsd)))
sampleDistMatrix <- as.matrix(sampleDist_cor)

s2s <- pheatmap(sampleDistMatrix,
                clustering_distance_rows = sampleDist_cor,
                clustering_distance_cols = sampleDist_cor,
                annotation_col = as.data.frame(colData(dds)[, c("genotype","treatment")]),
                main = "Sample-to-sample distance (1 - correlation)",
                treeheight_row = 75,
                treeheight_col = 60,
                cellheight = 25,
                cellwidth  = 25,
                fontsize = 9)
```
# 11. DESEQ CONTRASTS
```{r}
#------------------------ CONTRAST HELPER FUNCTION ------------------------#
condition_contrast <- function(dds, g1, t1, g0, t0) {
  X1 <- model.matrix(design(dds), 
                     data.frame(genotype = factor(g1, levels = levels(colData(dds)$genotype)),
                                treatment = factor(t1, levels = levels(colData(dds)$treatment))
                                )
                     )
  X0 <- model.matrix(design(dds),
                     data.frame(genotype = factor(g0, levels = levels(colData(dds)$genotype)),
                                treatment = factor(t0, levels = levels(colData(dds)$treatment))
                                )
                     )
as.numeric(X1 - X0)
}

#------------------------ RUNNING FUNCTION ------------------------#
# Build a contrast between two genotype/treatment combinations
condition_contrast <- function(dds, g1, t1, g0, t0) {
  X1 <- model.matrix(design(dds),
                     data.frame(genotype  = factor(g1, levels = levels(colData(dds)$genotype)),
                                treatment = factor(t1, levels = levels(colData(dds)$treatment)))
                     )
  X0 <- model.matrix(design(dds),
                     data.frame(genotype  = factor(g0, levels = levels(colData(dds)$genotype)),
                                treatment = factor(t0, levels = levels(colData(dds)$treatment)))
                     )
  as.numeric(X1 - X0)
}

# Run DESeq2 results or LFC shrinkage
run_result <- function(contrast = NULL, coef = NULL) {
  if (!is.null(coef)) {
    return(lfcShrink(dds, coef = coef, type = "apeglm"))
  }
  results(dds, contrast = contrast, alpha = 0.05)
}

#------------------------ GENOTYPE RESPONSES ------------------------#
# A. Leu response within each genotype: genes responding to amino-acid exposure
res_COL_Leu <- run_result(contrast = condition_contrast(dds,
                                                        "COL", "LEU", "COL", "GM"))
res_log2_Leu <- run_result(contrast = condition_contrast(dds, 
                                                         "log2-2", "LEU", "log2-2", "GM"))
res_abi5_Leu <- run_result(contrast = condition_contrast(dds, 
                                                         "abi5-7", "LEU", "abi5-7", "GM"))
#------------------------ GENOTYPExLEU INTERACTION ------------------------#
# D. These test whether the transcriptional response to LEU differs from COL.
res_log2_interaction <- run_result(coef = "genotypelog2.2.treatmentLEU")
res_abi5_interaction <- run_result(coef = "genotypeabi5.7.treatmentLEU")
```
# other CONTRAST TESTING
```{r BIOLOGICAL TESTING}
#------------------------ BASELINE GENOTYPE EFFECTS ------------------------#
# B. Tests whether mutants differ from COL under control conditions
res_log2_2_vs_COL_GM <- run_result(label = "04_log2_2_vs_COL_GM", contrast_vector = condition_contrast( dds, "log2-2", "GM", "COL", "GM"))
res_abi5_7_vs_COL_GM <- run_result(label = "05_abi5_7_vs_COL_GM", contrast_vector = condition_contrast( dds, "abi5-7", "GM", "COL", "GM"))

#------------------------ GENOTYPE EFFECTS UNDER LEU ------------------------#
# C. Testing if mutants differ from COl after Leu trt
res_log2_2_vs_COL_Leu <- run_result(label = "06_log2_2_vs_COL_Leu", contrast_vector = condition_contrast( dds, "log2-2", "LEU", "COL", "LEU"))
res_abi5_7_vs_COL_Leu <- run_result(label = "07_abi5_7_vs_COL_Leu", contrast_vector = condition_contrast( dds, "abi5-7", "LEU", "COL", "LEU"))

#------------------------ MUTANT COMPARISON OF LEU RESPONSE ------------------------#
# E. Identifies genes responding differently to Leu in abi5-7 and log2-2
res_abi5_vs_log2_interaction <- run_result(
  label = "10_abi5_7_vs_log2_2_Leu_response",
  contrast_vector = condition_contrast(dds, "abi5-7", "LEU", "abi5-7", "GM") - 
    condition_contrast(dds, "log2-2", "LEU", "log2-2", "GM")
)

#------------------------ SUMMARY ------------------------#
count_sig <- function(res, alpha = 0.05) {
  sum(!is.na(res$padj) & res$padj < alpha)
  }

summary_table <- data.frame(
  comparison = c(
    "COL LEU vs GM",
    "log2-2 LEU vs GM",
    "abi5-7 LEU vs GM",
    "log2-2 vs COL GM",
    "abi5-7 vs COL GM",
    "log2-2 vs COL LEU",
    "abi5-7 vs COL LEU",
    "log2-2 × LEU",
    "abi5-7 × LEU"
    ),
  significant_FDR_0.05 = c(
    count_sig(res_COL_Leu),
    count_sig(res_log2_2_Leu),
    count_sig(res_abi5_7_Leu),
    count_sig(res_log2_2_vs_COL_GM),
    count_sig(res_abi5_7_vs_COL_GM),
    count_sig(res_log2_2_vs_COL_Leu),
    count_sig(res_abi5_7_vs_COL_Leu),
    count_sig(res_log2_interaction),
    count_sig(res_abi5_interaction))
  )

summary_table
```
#  VOLCANO
```{r VOLCANO}
#------------------------ VOLCANO ------------------------#
plot_volcano <- function(res, title){
  df <- as.data.frame(res)
  df$status <- "NS"

  df$status[
    !is.na(df$padj) &
      df$padj < 0.05 &
      df$log2FoldChange > 1 ] <- "Up"

  df$status[
    !is.na(df$padj) &
      df$padj < 0.05 &
      df$log2FoldChange < -1 ] <- "Down"

  ggplot( df, aes( log2FoldChange, -log10(pvalue)) ) +
    geom_point( aes(color = status), alpha = 0.5 ) +
    scale_color_manual(
      values = c(
        "Up" = "red",
        "Down" = "blue",
        "NS" = "grey70") ) +
    theme_classic() +
    labs(title = title)
}

#------------------------ PLOTTING & SAVE ------------------------#
v1 <- plot_volcano( res_COL_Leu, "COL: Leu vs GM")
v1
v2 <- plot_volcano( res_log2_2_Leu, "log2-2: Leu vs GM")
v2
v3 <- plot_volcano( res_abi5_7_Leu, "abi5-7: Leu vs GM")
v3

#ggsave( file.path(graphics_dir,"Figure3A_COL_Volcano.pdf"), v1, width = 7, height = 6 )
#ggsave( file.path(graphics_dir,"Figure3B_log2_2_Volcano.pdf"), v2, width = 7, height = 6 )
#ggsave( file.path(graphics_dir,"Figure3C_abi5_7_Volcano.pdf"), v3, width = 7, height = 6 )
```
#  SPECIFIC CANDIDATE GENES AND PLOTS
```{r CANDIDATE GENES AND PLOTS}
#------------------------ CANDIDATE GENES & PLOTS ------------------------#
candidate_genes <- c( "AT1G01010", "AT1G01020", "AT1G01030" )

for(gene in candidate_genes){
  df_gene <- plotCounts(
    dds,
    gene = gene,
    intgroup = c("genotype","treatment"),
    returnData = TRUE )
  
  p <- ggplot(df_gene,
              aes(interaction(genotype,treatment), count)) +
    geom_boxplot() +
    geom_jitter(width = 0.15)
  print(p)
}

#ggsave(file.path(graphics_dir, paste0(gene, "_expression.pdf")), p, width = 6, height = 5 ) }
```
#  HEATMAP ALL
```{r}
#------------------------ HEATMAP HELPERS ------------------------#
ann_col <- as.data.frame(colData(dds)[ , c("genotype", "treatment")]) # annotations

# Get significant genes
get_sig_genes <- function(res, 
                          padj_cutoff = 0.05,
                          lfc_cutoff = 1.5) {
  rownames(subset(as.data.frame(res),
                  !is.na(padj) &
                    padj < padj_cutoff &
                    abs(log2FoldChange) > lfc_cutoff))
  }
prepare_heatmap_matrix <- function(expr_mat, genes) {
  hm <- expr_mat[genes, ]
  
  hm <- hm[apply(hm, 1, sd) > 0, ]  # Remove invariant genes
  
  hm <- t(scale(t(hm))) # Row z-score
  hm <- hm[complete.cases(hm), ]
  hm
  }

plot_DE_heatmap <- function(res, expr_mat, annotation_col, title) {
  genes <- get_sig_genes(res)
  if (length(genes) < 2) {
    message("Not enough significant genes for ", title)
    return(NULL)
  }
  
  hm <- prepare_heatmap_matrix(expr_mat, genes)

  pheatmap(hm,
           annotation_col = annotation_col,
           show_rownames = FALSE,
           angle_col = 45,
           color = colorRampPalette(c("navy", "white", "firebrick3"))(100),
           main = title)
  }

H1 <- plot_DE_heatmap(res_COL_Leu, mat, ann_col, "LEU vs GM")
#ggsave( file.path(graphics_dir,"01_Leu_vs_GM_heatmap.png"), H1, width = 10, height = 8)
H2 <- plot_DE_heatmap(res_log2_Leu, mat, ann_col, "log2-2: LEU vs GM")
H3 <- plot_DE_heatmap(res_abi5_Leu, mat, ann_col, "abi5-7: LEU vs GM")

plot_LEU_only_heatmap <- function(res, expr_mat, annotation_col, title) {
  genes <- get_sig_genes(res)

  if (length(genes) < 2) {
    message("Not enough significant genes for ", title)
    return(NULL)
  }

  keep <- annotation_col$treatment == "LEU"

  hm <- prepare_heatmap_matrix(expr_mat[ , keep], genes)

  pheatmap(hm,
           annotation_col = annotation_col[keep, ],
           show_rownames = FALSE,
           angle_col = 45,
           color = colorRampPalette(c("navy", "white", "firebrick3"))(100),
           main = title)
}

H1_1 <- plot_LEU_only_heatmap(res_COL_Leu, mat, ann_col, "COL-responsive genes (LEU samples)")
H2_1 <- plot_LEU_only_heatmap(res_log2_Leu, mat, ann_col, "log2-2 responsive genes (LEU samples)")
H3_1 <- plot_LEU_only_heatmap(res_abi5_Leu, mat, ann_col, "abi5-7 responsive genes (LEU samples)")
```
# 18. K MEANS CLUSTERING PLOTS
```{r K Means Clustering Plot}
#------------------------ KMEANS ------------------------#
# Elbow Method + Silhouette Analysis
genes <- get_sig_genes(res_COL_Leu) # Significant genes
keep <- ann_col$treatment == "LEU" # LEU samples only
hm <- prepare_heatmap_matrix(mat[ , keep], genes)

ann_sub <- ann_col[keep, ]
cat("Genes retained:", nrow(hm), "\n")

# Evaluate k values
k_range <- 2:15

wcss <- numeric(length(k_range))
silhouette_avg <- numeric(length(k_range))

set.seed(123)
for(i in seq_along(k_range)) {
  k <- k_range[i]
  km <- kmeans(hm, centers = k, nstart = 50)

  # Elbow Method
  wcss[i] <- km$tot.withinss

  # Silhouette Method
  sil <- silhouette(km$cluster, dist(hm))
  silhouette_avg[i] <- mean(sil[, 3])
}

# Elbow Plot
elbow_plot <- ggplot(data.frame(k = k_range, WCSS = wcss), aes(k, WCSS)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  theme_bw() +
  labs(title = "Elbow Method",
       x = "Number of Clusters (k)",
       y = "Within-Cluster Sum of Squares")

# Silhouette Plot
sil_plot <- ggplot(data.frame(k = k_range, silhouette = silhouette_avg),
                   aes(k, silhouette)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  theme_bw() +
  labs(title = "Silhouette Analysis",
       x = "Number of Clusters (k)",
       y = "Average Silhouette Width")

# Display plots side-by-side
grid.arrange(elbow_plot, 
             sil_plot,
             ncol = 2)
#ggsave( file.path(graphics_dir,"01_1_Kmeans.png"), sidebyside, width = 10, height = 8)

# Recommended k from silhouette
best_k <- k_range[which.max(silhouette_avg)]

cat("\nOptimal k based on silhouette score =", best_k, "\n")

# Run final k-means
km_final <- kmeans(hm, centers = best_k, nstart = 100)
table(km_final$cluster)

# K-means heatmap
H_kmeans <- pheatmap(hm, 
                     annotation_col = ann_sub, 
                     show_rownames = FALSE,
                     cluster_rows = FALSE,
                     cluster_cols = TRUE,
                     kmeans_k = best_k,
                     angle_col = 45,
                     color = colorRampPalette(
                       c("navy", "white", "firebrick3")
                       )(100),
                     main = paste0("LEU-responsive genes (k = ", best_k, ")")
                     )


#ggsave( file.path(graphics_dir,"01_1_Kmeans_k2.png"), H_kmeans, width = 10, height = 8)

# Export cluster 
 cluster_df <- data.frame(gene = rownames(hm), cluster = km_final$cluster)
 head(cluster_df)

# write.csv(
#   cluster_df,
 #  file.path(tables_dir,
#             "LEU_gene_clusters.csv"),
#   row.names = FALSE)

#  for(k in 2:8){
#  km <- kmeans(hm, centers = k,nstart = 50)
#  cat("\nK =", k, "\n")
#  print(table(km$cluster))
#  }
  
plot(k_range, silhouette_avg, type = "b", pch = 19)
```

# 19. LEU CLUSTERING HEATMAPS
```{r}
#------------------------ RUN KMEANS HEATMAP ------------------------#
plot_LEU_kmeans_heatmap <- function(res,
                                    expr_mat,
                                    annotation_col,
                                    title,
                                    padj_cutoff = 0.05,
                                    lfc_cutoff = 1.5,
                                    k = 5) {
  # Significant genes
  sig <- subset(as.data.frame(res),
                !is.na(padj) &
                  padj < padj_cutoff &
                  abs(log2FoldChange) > lfc_cutoff)

  if (nrow(sig) < 2) {
    message("Fewer than 2 significant genes found.")
    return(NULL)
  }

  genes <- rownames(sig)

  keep <- annotation_col$treatment == "LEU"  # LEU samples only

  hm <- expr_mat[genes, keep, drop = FALSE]
  ann <- annotation_col[keep, , drop = FALSE]

  # Force genotype order
  genotypes <- c("COL", "abi5-7", "log2-2")

  # Average replicates within genotype
  hm_avg <- do.call(cbind,
                    lapply(genotypes, function(g) {
                      idx <- ann$genotype == g
                      rowMeans(hm[, idx, drop = FALSE],
                               na.rm = TRUE)
                      })
                    )

  colnames(hm_avg) <- genotypes
  rownames(hm_avg) <- rownames(hm)

  hm_avg <- t(scale(t(hm_avg)))   # Row z-score

  # Remove rows with NA values
  hm_avg <- hm_avg[apply(hm_avg, 1, function(x) all(is.finite(x))), , drop = FALSE]

  # Keep results table synced with filtered matrix
  sig2 <- sig[rownames(hm_avg), ]

  # K-means clustering
  set.seed(123)

  km <- kmeans(hm_avg, centers = k, nstart = 50)
  cluster_sizes <- table(km$cluster)
  ord <- order(km$cluster)

  row_ann <- data.frame(Cluster = factor(km$cluster))
  rownames(row_ann) <- rownames(hm_avg)

  cluster_colors <- c("#1b9e77", "#d95f02", "#7570b3", "#e7298a", "#66a61e", "#e6ab02", "#a6761d", "#666666")

  ann_colors <- list(Cluster = setNames(cluster_colors[1:k], as.character(1:k)))

  ph <- pheatmap(hm_avg[ord, ],
                 annotation_row = row_ann[ord, , drop = FALSE],
                 annotation_colors = ann_colors,
                 cluster_rows = FALSE,
                 cluster_cols = FALSE, #already set before
                 show_rownames = FALSE,
                 show_colnames = TRUE,
                 annotation_names_row = FALSE,
                 gaps_row = cumsum(cluster_sizes)[-length(cluster_sizes)],
                 angle_col = 45,
                 color = colorRampPalette(c("navy", "white", "firebrick3"))(100),
                 main = paste0(title, " (k = ", k, ")"))

  cluster_df <- data.frame(gene = rownames(hm_avg), cluster = km$cluster, log2FC = sig2$log2FoldChange)

  return(list(plot = ph,
              clusters = cluster_df,
              kmeans = km,
              cluster_sizes = cluster_sizes,
              hm_avg = hm_avg)
  )
}

H1_2 <- plot_LEU_kmeans_heatmap(res = res_COL_Leu,
                              expr_mat = mat,
                              annotation_col = ann_col,
                              title = "K-Means clustering of LEU-responsive genes",
                              k = 5)
clust_df <- H1_2$clusters
table(clust_df$cluster)

tapply(abs(clust_df$log2FC), clust_df$cluster, mean)

#------------------------ WRITE CLUSTERS ------------------------#
#write_xlsx(split(clust_df, clust_df$cluster),  path = file.path(tables_dir, "LEU_gene_clusters.xlsx"))
#ggsave(file.path(graphics_dir, "01_2_cluster_leu_heatmap.png"), plot = H1_2$plot$gtable, width = 10, height = 8, dpi = 300)
```


```{r}
#------------------------ CLUSTERS ENRICHMENT ------------------------#
clusters <- sort(unique(clust_df$cluster))
clust_df$log2FC <- res_COL_Leu[match(clust_df$gene, rownames(res_COL_Leu)),
                               "log2FoldChange" ]

min_genes <- 5

GO_results <- list()
GO_sheets <- list()

for(cl in clusters){
  Clust_genes <- subset(clust_df, cluster == cl)$gene

  cat("Cluster", cl, "Genes:", length(Clust_genes), "\n")

  if(length(Clust_genes) >= min_genes){
    ego_res <- enrichGO(
      gene          = Clust_genes,
      OrgDb         = org.At.tair.db,
      keyType       = "TAIR",
      ont           = "BP",
      pAdjustMethod = "BH",
      pvalueCutoff  = 0.05,
      qvalueCutoff  = 0.05)

    # Remove redundant terms
    if(nrow(as.data.frame(ego_res)) > 0){
      ego_res <- simplify(ego_res, cutoff = 0.7, by = "p.adjust", select_fun = min)

      # Calculate term similarity matrix
      ego_res <- pairwise_termsim(ego_res)
      emapplot(ego_res, showCategory = 30)
      
      go_df <- as.data.frame(ego_res)
      cat("GO terms after simplification:", nrow(go_df), "\n" )

      GO_results[[paste0("Cluster", cl)]] <- ego_res
      GO_sheets[[paste0("Cluster_", cl)]] <- go_df
    }
  }
}

# Save all clusters in one workbook
#write_xlsx(GO_sheets, path = file.path(tables_dir, "GO_enrichment_clusters.xlsx"))

#------------------------ GO DOT PLOTS ------------------------#
go_plot_dir <- file.path(graphics_dir, "GO_dotplots")

for(cl_name in names(GO_results)) {
  ego_res <- GO_results[[cl_name]]
  
  if(nrow(as.data.frame(ego_res)) == 0) {
    cat(cl_name, ": No significant GO terms\n") 
    next
    }

p <- dotplot(ego_res, x = "Count", color = "p.adjust", size = "Count", orderBy = "p.adjust", showCategory = 15, font.size = 14) +
  ggtitle(paste("GO Enrichment -", cl_name)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
p
#ggsave(filename = file.path(graphics_dir, paste0(cl_name, "_GO_dotplot.png")), plot = p, width = 6, height = 6, dpi = 300)
#cat(cl_name, ": Dotplot saved\n")
}

gene_clusters <- split(clust_df$gene, clust_df$cluster)


# Combine simplified GO results

go_combined <- bind_rows(
  lapply(names(GO_sheets), function(cl) {

    df <- GO_sheets[[cl]]

    if (nrow(df) == 0) return(NULL)

    # Keep top 10 most significant terms
    df <- df %>%
      arrange(p.adjust) %>%
      slice_head(n = 10)

    df$Cluster <- gsub("Cluster_", "Cluster ", cl)
    # wrap GO terms
    df$Description <- str_wrap(df$Description, width = 35)
    df
  })
)

# Plot
p_go <- ggplot(go_combined,
               aes(x = Count,
                   y = reorder_within(Description,
                                      p.adjust,
                                      Cluster),
                   size = Count,
                   color = p.adjust)
               ) +
  geom_point(alpha = 0.9) +
  facet_wrap(~ Cluster,
             scales = "free_y",
             ncol = 2
             ) +
  scale_y_reordered() +
  scale_color_gradient(
    low = "hotpink",      # most significant
    high = "#233658",     # least significant
    name = "Adjusted p-value"
  ) +
  labs(title = "GO Biological Process Enrichment by K-means Cluster",
       x = "Gene Count",
       y = NULL,
       size = "Gene Count"
  ) +
  theme_bw(base_size = 12) +
  theme(strip.text = element_text(face = "bold", size = 12),
    axis.text.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 11),
    legend.title = element_text(face = "bold", size = 10),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 14))
p_go

#ggsave(file.path(graphics_dir, "GO_clusters_faceted.png"), p_go, width = 12, height = 10, dpi = 300)
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

hm_avg <- H1_2$hm_avg
km <- H1_2$kmeans

cluster_means <- hm %>%
  as.data.frame() %>%
  mutate(
    Cluster = factor(km$cluster)
  ) %>%
  group_by(Cluster) %>%
  summarise(
    across(everything(), mean),
    .groups = "drop"
  )

# Convert to long format
cluster_long <- cluster_means %>%
  pivot_longer(
    cols = -Cluster,
    names_to = "Genotype",
    values_to = "Mean_Zscore"
  )

# Plot
p_clusters <- ggplot(cluster_long,
                     aes(x = Genotype,
                         y = Mean_Zscore,
                         group = Cluster,
                         color = Cluster)
                     ) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3) +
  scale_color_manual(
    values = c(
      "#1b9e77",
      "#d95f02",
      "#7570b3",
      "#e7298a",
      "#66a61e",
      "blue",
      "yellow",
      "red"
    )
  ) +
  labs(
    title = "Average Expression Profiles of K-means Clusters",
    x = NULL,
    y = "Mean Z-score"
  ) +
  theme_bw(base_size = 12) +
  theme(
    plot.title = element_text(
      face = "bold",
      hjust = 0.5
    ),
    legend.title = element_blank()
  )
p_clusters

#ggsave(
#  file.path(graphics_dir, "Cluster_expression_profiles.png"),
#  p_clusters,
#  width = 7,
#  height = 5,
#  dpi = 300
#)
```


```{r}
hm_avg <- H1_2$hm_avg
km <- H1_2$kmeans

plot_df <- as.data.frame(hm_avg)
plot_df$Gene <- rownames(hm_avg)
plot_df$Cluster <- factor(km$cluster)

plot_long <- plot_df %>%
  pivot_longer(cols = -c(Gene, Cluster),
               names_to = "Genotype",
               values_to = "Expression")

# Control genotype order
plot_long$Genotype <- factor(plot_long$Genotype,
                           levels = c("COL", "abi5-7", "log2-2"))
cluster_means <- plot_long %>%
  group_by(Cluster, Genotype) %>%
  summarize(Mean_Expression = mean(Expression),
            .groups = "drop")

lineclust <- ggplot() +
  geom_line(data = plot_long,
            aes(x = Genotype,
                y = Expression,
                group = Gene),
            alpha = 0.1,
            color = "grey50") +
  geom_line(data = cluster_means,
            aes(x = Genotype,
                y = Mean_Expression,
                group = 1),
            color = "black",
            linewidth = 1.2) +
  geom_point(data = cluster_means,
             aes(x = Genotype,
                 y = Mean_Expression),
             color = "hotpink",
             size = 3) +
  facet_wrap(~Cluster, ncol = 3) +
  theme_bw() +
  labs(title = "Expression Profiles of K-means Clusters",
       subtitle = "Black lines represent mean cluster profiles",
       x = NULL,
       y = "Mean Z-score") +
  theme(legend.position = "none",
        strip.text = element_text(face = "bold",
                                  size = 12),
        axis.text.x = element_text(angle = 45,
                                   face = "bold",
                                   hjust = 1),
        plot.title = element_text(face = "bold",
                                  hjust = 0.5)
        )

#ggsave(file.path(graphics_dir, "GO_clusters_line.png"), lineclust, width = 10, height = 8, dpi = 300)
```


```{r}
for(cl_name in names(GO_results)) {

  ego_res <- GO_results[[cl_name]]

  if(nrow(as.data.frame(ego_res)) == 0) next

  p <- emapplot(ego_res, showCategory = 30)

  ggsave(file.path(graphics_dir, paste0(cl_name,"_emap.png")), width = 8, height = 6)
  }

p <- dotplot(ego_res, x = "Count", color = "p.adjust", showCategory = 15, orderBy = "p.adjust", font.size = 14) +
  guides(size = "none") +
  theme_bw()

p <- dotplot(ego_res, x = "Count", color = "p.adjust", showCategory = 15) +
  scale_size_continuous(name = "Gene Count")

p <- dotplot(ego_res, x = "Count", color = "p.adjust", size = "Count",
  showCategory = 15)
```


```{r}
#------------------------ GSEA ENRICHMENT ------------------------#
gsea_res <- res_COL_Leu
gsea_res <- gsea_res[!is.na(gsea_res$log2FoldChange), ]

gene_list <- gsea_res$log2FoldChange
names(gene_list) <- rownames(gsea_res)
gene_list <- sort(gene_list, decreasing = TRUE)
head(gene_list)
gsea_BP <- gseGO(
  geneList      = gene_list,
  OrgDb         = org.At.tair.db,
  keyType       = "TAIR",
  ont           = "BP",
  minGSSize     = 10,
  maxGSSize     = 500,
  pvalueCutoff  = 0.05,
  verbose       = FALSE
)

gsea_df <- as.data.frame(gsea_BP)

head(gsea_df)

#write_xlsx(
#  gsea_df,
#  file.path(
#    tables_dir,
#    "GSEA_BP_results.xlsx"
#  )
#)
gsea_BP <- pairwise_termsim(gsea_BP)
GSEA_dot <- dotplot(
  gsea_BP,
  showCategory = 20,
  split = ".sign"
) +
  facet_grid(. ~ .sign) +
  theme_bw()

#ggsave(
#  file.path(
#    graphics_dir,
#    "GSEA_dotplot.png"
#  ),
#  GSEA_dot,
#  width = 12,
#  height = 8,
#  dpi = 300
#)
GSEA_emap <- emapplot(
  gsea_BP,
  showCategory = 30
)

#ggsave(
#  file.path(
#    graphics_dir,
#    "GSEA_emapplot.png"
#  ),
#  GSEA_emap,
#  width = 12,
#  height = 10,
#  dpi = 300
#)

GSEA_ridge <- ridgeplot(
  gsea_BP,
  showCategory = 20
)

#ggsave(
#  file.path(
#    graphics_dir,
#    "GSEA_ridgeplot.png"
#  ),
#  GSEA_ridge,
#  width = 12,
#  height = 10,
#  dpi = 300
#)

gseaplot2(gsea_BP,
  geneSetID = 1,
  title = gsea_BP@result$Description[1]
)
gseaplot2(gsea_BP, geneSetID = "GO:0009733")
```


```{r}
#------------------------ VENNDIAGRAM ------------------------#
library(ggpubr)
library(ggVennDiagram)

sig_COL <- rownames(subset(res_COL_Leu, 
                           padj < 0.05 & 
                             abs(log2FoldChange) > 1.5))

sig_abi5 <- rownames(subset(res_abi5_7_Leu,
                            padj < 0.05 & 
                              abs(log2FoldChange) > 1.5))

venn_list <- list(COL = sig_COL, abi5 = sig_abi5)
V1 <- ggVennDiagram(venn_list, label_alpha = 0) +
  scale_fill_gradient(
    low = "white",
    high = "steelblue") + 
  theme_bw()

#ggsave(file.path(graphics_dir, "COL_vs_abi5_Venn.png"), V1, width = 8, height = 6, dpi = 300)
```


```{r}
#------------------------ DIVERGENT RESPONSES COL & LEU ------------------------#
# BUILD COMPARISON TABLE 
COL <- as.data.frame(res_COL_Leu)
abi5 <- as.data.frame(res_abi5_Leu)

COL$gene <- rownames(COL)
abi5$gene <- rownames(abi5)

compare_all <- merge(COL, abi5, by = "gene", suffixes = c("_COL", "_abi5"))

compare_all <- compare_all %>%
  filter( !is.na(log2FoldChange_COL), 
          !is.na(log2FoldChange_abi5) )

# ADD CLUSTER INFO       #
compare_df <- compare_all %>%
  left_join( clust_df[, c("gene", "cluster")], by = "gene" )

# RESPONSE DIFFERENCES   #
compare_df <- compare_df %>%
  mutate(deltaFC = log2FoldChange_abi5 - log2FoldChange_COL,
         Divergent = !is.na(cluster) &
           abs(deltaFC) >= 1.5 &
           (padj_COL < 0.05 | padj_abi5 < 0.05),
         Opposite = !is.na(cluster) &
           sign(log2FoldChange_COL) !=
           sign(log2FoldChange_abi5) &
           (padj_COL < 0.05 | padj_abi5 < 0.05) )

# CORRELATION
cor_val <- cor(compare_df$log2FoldChange_COL,
               compare_df$log2FoldChange_abi5,
               use = "complete.obs")
cat("Correlation =", round(cor_val, 3), "\n")

# DIVERGENT GENES
divergent_genes <- compare_df %>%
  filter(Divergent) %>%
  arrange(desc(abs(deltaFC)))

# OPPOSITE RESPONSE
opposite_response <- compare_df %>%
  filter(Opposite) %>%
  arrange(desc(abs(deltaFC)))
cat("Opposite response genes:", nrow(opposite_response), "\n")

# CLUSTER SUMMARY        
cluster_summary <- divergent_genes %>%
  group_by(cluster) %>%
  summarise( n_genes = n(),
             mean_deltaFC = mean(abs(deltaFC)) ) %>%
  arrange(desc(n_genes))
cluster_summary

# SCATTERPLOT
top_labels <- divergent_genes %>%
  slice_max(order_by = abs(deltaFC), n = 20)

p_compare <- ggplot() +
  # all genes
  geom_point(data = compare_df,
             aes(x = log2FoldChange_COL,
                 y = log2FoldChange_abi5),
             color = "grey80",
             alpha = 0.25,
             size = 1 ) +

  # clustered divergent genes
  geom_point(data = divergent_genes,
             aes(x = log2FoldChange_COL,
                 y = log2FoldChange_abi5,
                 color = factor(cluster) ),
             size = 2.5) +
  geom_abline(slope = 1, intercept = 0, linetype = 2) +

  geom_text_repel(data = top_labels,
                  aes(x = log2FoldChange_COL,
                      y = log2FoldChange_abi5,
                      label = gene ),
                  size = 3) +
  theme_bw() +
  labs(title = paste0("COL vs abi5 Leucine Response (r = ",
                      round(cor_val, 3), ")" ),
       x = "COL log2FC",
       y = "abi5 log2FC",
       color = "Cluster" )
p_compare

#ggsave(file.path( graphics_dir, "COL_abi5_divergent_genes.png"),
#        p_compare,
#        width = 8,
#        height = 6,
#        dpi = 300)
```


```{r}
# FOCUS ON CLUSTER 1 #
cluster1_div <- divergent_genes %>%
filter(cluster == 1) %>%
arrange(desc(abs(deltaFC)))

cat("Cluster 1 divergent genes:", nrow(cluster1_div),"\n")

# ANNOTATE GENES #
cluster1_annot <- AnnotationDbi::select(org.At.tair.db,
                                        keys = cluster1_div$gene,
                                        keytype = "TAIR",
                                        columns = c("TAIR",
                                                    "SYMBOL",
                                                    "GENENAME")
                                        )

cluster1_results <- cluster1_div %>%
  left_join(cluster1_annot, by = c("gene" = "TAIR")) %>%
  arrange(desc(abs(deltaFC)))

cluster1_results %>%
  select(gene,
         SYMBOL,
         GENENAME,
         log2FoldChange_COL,
         log2FoldChange_abi5,
         deltaFC,
         padj_COL,
         padj_abi5) %>%
  head(50)

# CLUSTER 1 HEATMAP #
cluster1_genes <- cluster1_results$gene

hm_cluster1 <- hm_avg[rownames(hm_avg) %in% cluster1_genes, ]

ann_genotype <- data.frame(genotype = c( "COL", "abi5-7", "log2-2"))

rownames(ann_genotype) <- c("COL", "abi5-7", "log2-2")

clust1_hm <- pheatmap(hm_cluster1, scale = "row", cluster_rows = TRUE, cluster_cols = FALSE, annotation_col = ann_genotype)
 ggsave(
   file.path(
     graphics_dir,
     "COL_abi5_divergent_hm.png"),
   clust1_hm,
   width = 8,
   height = 8,
   dpi = 300
 )

# ABI5-LIKE CANDIDATES #
cluster1_results %>% filter(
  grepl( "ABI|EM|LEA|DOG|OLE|CRU|CRA|RAB",
         SYMBOL,
         ignore.case = TRUE)) %>%
   select(gene,
          SYMBOL,
          GENENAME,
          deltaFC)

# SAVE RESULTS #
# write.csv(
# cluster1_results,
# file.path(
# tables_dir,
# "Cluster1_Divergent_Genes.csv"
# ),
# row.names = FALSE
# )
```


```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)
library(clusterProfiler)
library(org.At.tair.db)
library(AnnotationDbi)


head(opposite_response %>%
    select( gene,
            cluster,
            log2FoldChange_COL,
            log2FoldChange_abi5,
            deltaFC ), 50 )
ann_genotype <- data.frame(genotype = c("COL", "abi5-7", "log2-2"))

rownames(ann_genotype) <- c("COL", "abi5-7", "log2-2")

pheatmap( hm_cluster1,
          scale = "row",
          cluster_rows = TRUE,
          cluster_cols = FALSE,
          annotation_col = ann_genotype)

opposite_response %>%
  group_by(cluster) %>%
  summarise(n_genes = n(), mean_deltaFC = mean(abs(deltaFC)) ) %>%
  arrange(desc(n_genes))

divergent_genes %>%
  group_by(cluster) %>%
  summarise( n_genes = n(),
             mean_deltaFC = mean(abs(deltaFC))) %>%
  arrange(desc(n_genes))

cluster1_opposite <- opposite_response %>%
  filter(cluster == 1) %>%
  arrange(desc(abs(deltaFC)))

head(cluster1_opposite %>%
       select(gene,
              log2FoldChange_COL,
              log2FoldChange_abi5,
              deltaFC ), 50 )

cluster5_opposite <- opposite_response %>%
  filter(cluster == 5) %>%
  arrange(desc(abs(deltaFC)))

head(cluster5_opposite %>%
       select(gene,
              log2FoldChange_COL,
              log2FoldChange_abi5,
              deltaFC), 50 )

ggplot(opposite_response,
       aes(x = factor(cluster),
           fill = factor(cluster))) +
  geom_bar() +
  theme_bw() +
  labs( x = "Cluster",
        y = "Number of opposite-response genes",
        title = "Opposite leucine responses between COL and abi5")

cluster1_div <- divergent_genes %>%
  filter(cluster == 1) %>%
  arrange(desc(abs(deltaFC)))

cluster1_div %>%
  select( gene,
          log2FoldChange_COL,
          log2FoldChange_abi5,
          deltaFC,
          padj_COL,
          padj_abi5) %>%
  head(50)

cluster1_genes <- cluster1_div$gene

hm_cluster1 <- hm_avg[rownames(hm_avg) %in% cluster1_genes, ]
annotation_col = ann

cluster1_COL <- cluster1_div %>%
  filter(deltaFC < 0) %>%
  arrange(deltaFC)
cluster1_abi5 <- cluster1_div %>%
  filter(deltaFC > 0) %>%
  arrange(desc(deltaFC))

ego_cluster1_COL <- enrichGO(gene = cluster1_COL$gene,
                             OrgDb = org.At.tair.db,
                             keyType = "TAIR",
                             ont = "BP")

ego_cluster1_abi5 <- enrichGO(gene = cluster1_abi5$gene,
                              OrgDb = org.At.tair.db,
                              keyType = "TAIR",
                              ont = "BP")

#write.csv(cluster1_div, "Cluster1_divergent_genes.csv", row.names = FALSE)

cluster1_annot <- AnnotationDbi::select(org.At.tair.db,
                                        keys = cluster1_div$gene,
                                        keytype = "TAIR",
                                        columns = c( "TAIR", 
                                                     "SYMBOL",
                                                     "GENENAME"))

cluster1_results <- cluster1_div %>%
  left_join(cluster1_annot, by = c("gene" = "TAIR")) %>%
  arrange(desc(abs(deltaFC)))

cluster1_results %>%
  select(gene,
         SYMBOL,
         GENENAME,
         log2FoldChange_COL,
         log2FoldChange_abi5,
         deltaFC) %>%
  head(50)

ggplot(cluster1_div,
       aes(log2FoldChange_COL,
           log2FoldChange_abi5)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  theme_bw()
```

```{r}
# CLUSTER 5 ONLY         #

cluster5_div <- divergent_genes %>%
  filter(cluster == 5) %>%
  arrange(desc(abs(deltaFC)))

cat("Cluster 5 divergent genes:", nrow(cluster5_div),  "\n")


# ANNOTATE GENES         #
cluster5_annot <- AnnotationDbi::select(
  org.At.tair.db,
  keys = cluster5_div$gene,
  keytype = "TAIR",
  columns = c( "TAIR", "SYMBOL", "GENENAME" ) )

cluster5_results <- cluster5_div %>%
  left_join(cluster5_annot,
            by = c("gene" = "TAIR")) %>%
  arrange(desc(abs(deltaFC)))

cluster5_results %>%
  select(gene,
         SYMBOL,
         GENENAME,
         log2FoldChange_COL,
         log2FoldChange_abi5,
         deltaFC,
         padj_COL,
         padj_abi5 ) %>%
  head(50)


# CLUSTER 5 HEATMAP      #
cluster5_genes <- cluster5_results$gene

hm_cluster5 <- hm_avg[rownames(hm_avg) %in% cluster5_genes, ]

ann_genotype <- data.frame(
  genotype = c("COL", "abi5-7", "log2-2"))

rownames(ann_genotype) <- c("COL", "abi5-7", "log2-2")

hm_clust5_abivscol <- pheatmap( hm_cluster5, scale = "row", cluster_rows = TRUE, cluster_cols = FALSE, annotation_col = ann_genotype)

#ggsave(file.path(graphics_dir, "COL_abi5_divergent_hm5.png"), hm_clust5_abivscol, width = 12, height = 10, dpi = 300)

# OPPOSITE RESPONSE CLUSTERED ONLY 
opposite_response %>%
  group_by(cluster) %>%
  summarise(n_genes = n(), mean_deltaFC = mean(abs(deltaFC)) ) %>%
  arrange(desc(n_genes))


# SAVE CANDIDATES        #
# write.csv(
#   cluster1_results,
#   file.path(
#     tables_dir,
#     "Cluster1_Divergent_Genes.csv"
#   ),
#   row.names = FALSE
# )
```

```{r}
if (params$session_info) {
  sessionInfo()
}
```